"""baseline: current schema

Revision ID: 3914ece79b88
Revises: 
Create Date: 2026-08-05 16:31:57.482890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3914ece79b88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('migration_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('migration_name', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('migration_name', 'entity_type', 'legacy_id', name='uq_migration_checkpoint_legacy')
    )
    with op.batch_alter_table('migration_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_checkpoints_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_checkpoints_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_checkpoints_migration_name'), ['migration_name'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_public_key'), ['public_key'], unique=True)

    op.create_table('admin_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_activities_admin_id'), ['admin_id'], unique=False)

    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('max_pairs_per_project', sa.Integer(), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=False),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('duration_type', sa.String(length=20), nullable=True),
    sa.Column('duration_value', sa.Integer(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('total_project_limit', sa.Integer(), nullable=True),
    sa.Column('total_scan_limit', sa.Integer(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_trial_plan', sa.Boolean(), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_config_key'), ['config_key'], unique=True)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_public_key'), ['public_key'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_public_key'), ['public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('subscription_taken_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscribed_project_limit', sa.Integer(), nullable=True),
    sa.Column('subscribed_scan_limit', sa.Integer(), nullable=True),
    sa.Column('projects_used', sa.Integer(), nullable=True),
    sa.Column('scans_used', sa.Integer(), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('challenge_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('first_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_challenge_id'), ['challenge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_otp_codes_email'), ['email'], unique=False)
        batch_op.create_index('ix_otp_email_purpose', ['email', 'purpose'], unique=False)
        batch_op.create_index('ix_otp_expires_at', ['expires_at'], unique=False)

    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('offer_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('purchased_project_limit', sa.Integer(), nullable=True),
    sa.Column('purchased_scan_limit', sa.Integer(), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payment_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_orders_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_orders_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('user_project_index', sa.Integer(), nullable=True),
    sa.Column('scanner_url', sa.Text(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('qr_code_filename', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_admin_id'), ['owner_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('trial_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=False),
    sa.Column('trial_project_limit', sa.Integer(), nullable=True),
    sa.Column('trial_scan_limit', sa.Integer(), nullable=True),
    sa.Column('trial_extended', sa.Boolean(), nullable=True),
    sa.Column('extended_days', sa.Integer(), nullable=True),
    sa.Column('extended_by', sa.Integer(), nullable=True),
    sa.Column('extended_at', sa.DateTime(), nullable=True),
    sa.Column('extended_reason', sa.Text(), nullable=True),
    sa.Column('trial_converted', sa.Boolean(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('converted_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['converted_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['extended_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_login_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_login_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_activities_user_id'), ['user_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_user')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('legacy_project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_published_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_published_version_id'], ['experience_versions.id'], name='fk_experiences_current_published_version', use_alter=True),
    sa.ForeignKeyConstraint(['legacy_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_legacy_project_id'), ['legacy_project_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_experiences_public_key'), ['public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_experiences_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('project_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pair_index', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('video_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('original_image_name', sa.String(length=255), nullable=True),
    sa.Column('original_video_name', sa.String(length=255), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('video_size', sa.Integer(), nullable=True),
    sa.Column('marker_mode', sa.String(length=20), nullable=True),
    sa.Column('marker_crop_x', sa.Float(), nullable=True),
    sa.Column('marker_crop_y', sa.Float(), nullable=True),
    sa.Column('marker_crop_width', sa.Float(), nullable=True),
    sa.Column('marker_crop_height', sa.Float(), nullable=True),
    sa.Column('marker_rotation', sa.Integer(), nullable=True),
    sa.Column('marker_original_width', sa.Integer(), nullable=True),
    sa.Column('marker_original_height', sa.Integer(), nullable=True),
    sa.Column('marker_processed_width', sa.Integer(), nullable=True),
    sa.Column('marker_processed_height', sa.Integer(), nullable=True),
    sa.Column('marker_source_size_bytes', sa.Integer(), nullable=True),
    sa.Column('marker_processed_size_bytes', sa.Integer(), nullable=True),
    sa.Column('marker_display_orientation', sa.String(length=20), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('video_processing_status', sa.String(length=20), nullable=True),
    sa.Column('feature_extraction_status', sa.String(length=20), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('feature_extraction_time', sa.Float(), nullable=True),
    sa.Column('video_compression_time', sa.Float(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('last_matched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'pair_index', name='uq_project_pair_index')
    )
    with op.batch_alter_table('project_pairs', schema=None) as batch_op:
        batch_op.create_index('ix_project_pairs_processed', ['project_id', 'is_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_pairs_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_project_pairs_status', ['project_id', 'processing_status'], unique=False)
        batch_op.create_index('ix_project_pairs_video_status', ['video_processing_status'], unique=False)

    op.create_table('experience_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('publication_checksum', sa.String(length=128), nullable=True),
    sa.Column('publication_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('processing_snapshot_json', sa.Text(), nullable=True),
    sa.Column('publication_notes', sa.Text(), nullable=True),
    sa.Column('rollback_source_version_id', sa.Integer(), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('public_destination', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rollback_source_version_id'], ['experience_versions.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['experience_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'version_number', name='uq_experience_version_number')
    )
    with op.batch_alter_table('experience_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_versions_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_versions_publication_idempotency_key'), ['publication_idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_versions_published_by_user_id'), ['published_by_user_id'], unique=False)

    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_session_id', sa.String(length=100), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('counted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['project_pairs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scan_session_id', name='uq_scan_logs_user_session')
    )
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_logs_scan_session_id'), ['scan_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_logs_user_id'), ['user_id'], unique=False)

    op.create_table('triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('experience_version_id', sa.Integer(), nullable=True),
    sa.Column('legacy_project_pair_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['experience_version_id'], ['experience_versions.id'], ),
    sa.ForeignKeyConstraint(['legacy_project_pair_id'], ['project_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triggers_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triggers_experience_version_id'), ['experience_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triggers_legacy_project_pair_id'), ['legacy_project_pair_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_triggers_public_key'), ['public_key'], unique=True)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_diagnostics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_processing_job_workspace_idempotency')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_public_key'), ['public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_processing_jobs_trigger_id'), ['trigger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('recognition_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('algorithm_version', sa.String(length=80), nullable=True),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_id', 'artifact_type', 'storage_key', name='uq_trigger_artifact_storage')
    )
    with op.batch_alter_table('recognition_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_artifacts_trigger_id'), ['trigger_id'], unique=False)

    op.create_table('trigger_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_id', 'asset_id', 'role', name='uq_trigger_asset_role')
    )
    with op.batch_alter_table('trigger_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trigger_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_assets_trigger_id'), ['trigger_id'], unique=False)

    op.create_table('experience_version_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_version_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('inclusion_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('reference_image_asset_id', sa.Integer(), nullable=True),
    sa.Column('video_asset_id', sa.Integer(), nullable=True),
    sa.Column('recognition_artifact_id', sa.Integer(), nullable=True),
    sa.Column('fallback_asset_id', sa.Integer(), nullable=True),
    sa.Column('creator_label', sa.String(length=255), nullable=True),
    sa.Column('processing_snapshot_json', sa.Text(), nullable=True),
    sa.Column('source_revision_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_version_id'], ['experience_versions.id'], ),
    sa.ForeignKeyConstraint(['fallback_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recognition_artifact_id'], ['recognition_artifacts.id'], ),
    sa.ForeignKeyConstraint(['reference_image_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_version_id', 'trigger_id', name='uq_experience_version_trigger')
    )
    with op.batch_alter_table('experience_version_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_version_triggers_experience_version_id'), ['experience_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_version_triggers_trigger_id'), ['trigger_id'], unique=False)

    op.create_table('processing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('creator_message', sa.Text(), nullable=True),
    sa.Column('diagnostic_code', sa.String(length=80), nullable=True),
    sa.Column('diagnostic_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_trigger_id'), ['trigger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_trigger_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_experience_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_event_type'))

    op.drop_table('processing_events')
    with op.batch_alter_table('experience_version_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_version_triggers_trigger_id'))
        batch_op.drop_index(batch_op.f('ix_experience_version_triggers_experience_version_id'))

    op.drop_table('experience_version_triggers')
    with op.batch_alter_table('trigger_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trigger_assets_trigger_id'))
        batch_op.drop_index(batch_op.f('ix_trigger_assets_asset_id'))

    op.drop_table('trigger_assets')
    with op.batch_alter_table('recognition_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_artifacts_trigger_id'))

    op.drop_table('recognition_artifacts')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_trigger_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_public_key'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_experience_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triggers_public_key'))
        batch_op.drop_index(batch_op.f('ix_triggers_legacy_project_pair_id'))
        batch_op.drop_index(batch_op.f('ix_triggers_experience_version_id'))
        batch_op.drop_index(batch_op.f('ix_triggers_experience_id'))

    op.drop_table('triggers')
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_scan_session_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_project_id'))

    op.drop_table('scan_logs')
    with op.batch_alter_table('experience_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_versions_published_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_experience_versions_publication_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_experience_versions_experience_id'))
        batch_op.drop_index(batch_op.f('ix_experience_versions_created_by_user_id'))

    op.drop_table('experience_versions')
    with op.batch_alter_table('project_pairs', schema=None) as batch_op:
        batch_op.drop_index('ix_project_pairs_video_status')
        batch_op.drop_index('ix_project_pairs_status')
        batch_op.drop_index(batch_op.f('ix_project_pairs_project_id'))
        batch_op.drop_index('ix_project_pairs_processed')

    op.drop_table('project_pairs')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_experiences_public_key'))
        batch_op.drop_index(batch_op.f('ix_experiences_legacy_project_id'))
        batch_op.drop_index(batch_op.f('ix_experiences_created_by_user_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('user_login_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_activities_user_id'))

    op.drop_table('user_login_activities')
    op.drop_table('trial_details')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_admin_id'))

    op.drop_table('projects')
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_orders_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_order_id'))

    op.drop_table('payment_orders')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_expires_at')
        batch_op.drop_index('ix_otp_email_purpose')
        batch_op.drop_index(batch_op.f('ix_otp_codes_email'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_challenge_id'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_assets_public_key'))

    op.drop_table('assets')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_public_key'))
        batch_op.drop_index(batch_op.f('ix_workspaces_organization_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_config_key'))

    op.drop_table('system_configs')
    op.drop_table('subscription_plans')
    with op.batch_alter_table('admin_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_activities_admin_id'))

    op.drop_table('admin_activities')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_public_key'))

    op.drop_table('organizations')
    with op.batch_alter_table('migration_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_checkpoints_migration_name'))
        batch_op.drop_index(batch_op.f('ix_migration_checkpoints_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_migration_checkpoints_entity_type'))

    op.drop_table('migration_checkpoints')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
