"""Phase 1 migration foundation tests.

Covers the Flask-Migrate/Alembic scaffolding added in this phase: the
`migrations/` directory and its single baseline revision
(3914ece79b88, "baseline: current schema"), generated by autogenerating
against a truly empty database so its upgrade() recreates every table
`models.py` defines.

Two different app objects are used deliberately:

- `app_module` (the existing isolated_app fixture from tests/conftest.py)
  imports the real app.py. Importing app.py always runs
  `with app.app_context(): db.create_all(); ensure_marker_schema(); ...`
  at module import time (see app.py ~line 672), so by the time this fixture
  yields, the schema already exists - exactly like a real pre-Alembic boot.
  This is used for the "baseline stamp against an already-created database"
  scenarios, matching how a real deployment will adopt this.

- `bare_migration_app` (fixture below) builds minimal Flask apps bound to
  the same `models.db` object/metadata, each pointed at its own throwaway
  tmp_path sqlite file that has never had db.create_all() run against it.
  This is the only way to exercise "upgrade against a genuinely clean
  database", because the real app module's eager db.create_all() makes
  that scenario unobservable through app.py directly. It never touches
  app.py or its migrations directory contents, and its engines are
  disposed at teardown (mirroring isolated_app's own cleanup), so it can't
  leak open sqlite connections into the isolated_app fixture or any other
  test across the full session.
"""
import sqlite3
from pathlib import Path

import pytest
from flask import Flask
from flask_migrate import Migrate
from flask_migrate import current as migrate_current
from flask_migrate import stamp as migrate_stamp
from flask_migrate import upgrade as migrate_upgrade
from sqlalchemy import inspect, text

from models import db as shared_db

MIGRATIONS_DIR = str(Path(__file__).resolve().parents[2] / "migrations")
BASELINE_REVISION = "3914ece79b88"


@pytest.fixture()
def bare_migration_app(tmp_path):
    """Factory for a minimal Flask app bound to models.db, pointed at its own
    tmp_path sqlite file. Every app this factory creates gets its engine
    disposed at teardown - the same cleanup tests/conftest.py's isolated_app
    fixture already does for the real app - so these throwaway apps don't
    accumulate open sqlite engines/connections across the full test session
    (models.db is a single process-wide object reused by every test).
    """
    created = []

    def _make(name):
        app = Flask(f"migration_test_{name}")
        app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{(tmp_path / name).as_posix()}"
        app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
        app.secret_key = "migration-test-only"
        shared_db.init_app(app)
        Migrate(app, shared_db, directory=MIGRATIONS_DIR)
        created.append(app)
        return app

    yield _make

    for app in created:
        with app.app_context():
            shared_db.session.remove()
            shared_db.engine.dispose()


def _sqlite_table_names(db_path):
    con = sqlite3.connect(str(db_path))
    try:
        rows = con.execute("select name from sqlite_master where type='table'").fetchall()
    finally:
        con.close()
    return {row[0] for row in rows}


def test_migrate_extension_initializes_cleanly(bare_migration_app):
    """Flask-Migrate can be imported and instantiated against the app/db
    objects without error, and registers itself under app.extensions."""
    app = bare_migration_app("init_check.db")
    with app.app_context():
        assert "migrate" in app.extensions
        assert app.extensions["migrate"].db is shared_db
        assert app.extensions["migrate"].directory == MIGRATIONS_DIR


def test_clean_database_upgrade_creates_full_schema(tmp_path, bare_migration_app):
    """flask db upgrade, run against nothing, produces every table models.py
    defines (plus alembic's own bookkeeping table)."""
    db_path = tmp_path / "clean_upgrade.db"
    assert not db_path.exists()
    app = bare_migration_app("clean_upgrade.db")

    with app.app_context():
        migrate_upgrade()

    tables = _sqlite_table_names(db_path)
    expected_model_tables = {table.name for table in shared_db.metadata.sorted_tables}
    assert expected_model_tables, "sanity check: models.py should define tables"
    assert expected_model_tables.issubset(tables)
    assert "alembic_version" in tables

    with app.app_context():
        version_rows = shared_db.session.execute(text("select version_num from alembic_version")).fetchall()
    assert [row[0] for row in version_rows] == [BASELINE_REVISION]


def test_upgrade_is_idempotent(tmp_path, bare_migration_app):
    """Running flask db upgrade twice back to back does not error and does
    not double-apply (single alembic_version row, same table set)."""
    db_path = tmp_path / "idempotent_upgrade.db"
    app = bare_migration_app("idempotent_upgrade.db")

    with app.app_context():
        migrate_upgrade()
        tables_after_first = _sqlite_table_names(db_path)
        migrate_upgrade()  # must be a clean no-op, not an error
        tables_after_second = _sqlite_table_names(db_path)
        version_rows = shared_db.session.execute(text("select version_num from alembic_version")).fetchall()

    assert tables_after_first == tables_after_second
    assert [row[0] for row in version_rows] == [BASELINE_REVISION]


def test_baseline_stamp_preserves_existing_schema_and_data(app_module, db_session):
    """Stamping an existing (pre-Alembic, db.create_all()-built) database at
    the baseline revision must not create/drop/alter any table, and must not
    touch existing row data - it only records "this DB is already here"."""
    inspector = inspect(app_module.db.engine)
    tables_before = set(inspector.get_table_names())
    assert "alembic_version" not in tables_before, "fixture DB should predate Alembic"

    plan = app_module.SubscriptionPlan.query.filter_by(is_trial_plan=True).first()
    assert plan is not None
    plan_id = plan.id
    plan_snapshot = {column.name: getattr(plan, column.name) for column in plan.__table__.columns}

    migrate_stamp(revision=BASELINE_REVISION)

    inspector = inspect(app_module.db.engine)
    tables_after = set(inspector.get_table_names())
    assert tables_after == tables_before | {"alembic_version"}, (
        "stamp must only add the bookkeeping table, never alter/drop existing tables"
    )

    version_rows = app_module.db.session.execute(text("select version_num from alembic_version")).fetchall()
    assert [row[0] for row in version_rows] == [BASELINE_REVISION]

    plan_after = app_module.db.session.get(app_module.SubscriptionPlan, plan_id)
    for column_name, value in plan_snapshot.items():
        assert getattr(plan_after, column_name) == value, f"column {column_name} changed after stamp"


def test_flask_db_current_reports_baseline_after_stamp(app_module, db_session):
    """`flask db current` (flask_migrate.current) shows nothing before the
    stamp and the baseline revision afterward - the exact check the
    production rollout runbook relies on."""
    with app_module.app.app_context():
        before_rows = app_module.db.session.execute(
            text("select name from sqlite_master where type='table' and name='alembic_version'")
        ).fetchall()
    assert before_rows == []

    migrate_stamp(revision=BASELINE_REVISION)

    version_rows = app_module.db.session.execute(text("select version_num from alembic_version")).fetchall()
    assert [row[0] for row in version_rows] == [BASELINE_REVISION]


def test_alembic_tests_coexist_with_isolated_app_fixture(app_module, db_session, normal_user):
    """Confirms the Alembic-focused tests above don't leak sqlite files or
    module state into the existing isolated_app fixture pattern - ordinary
    fixture-driven user lookups still behave exactly as elsewhere in the
    suite when this file runs in the same session as the rest of tests/."""
    found = app_module.User.query.filter_by(email="user@example.com").first()
    assert found is not None
    assert found.id == normal_user.id
